// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUIXY0RwjNeGmJRU9umNu0Q87Ghfdiink',
    appId: '1:1014655734942:web:97e39db5c0c4e8c75fd78f',
    messagingSenderId: '1014655734942',
    projectId: 'thilshan-spotify',
    authDomain: 'thilshan-spotify.firebaseapp.com',
    storageBucket: 'thilshan-spotify.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdWcDnSwLube-3LQJpDZc6eaqNsw70YjY',
    appId: '1:1014655734942:android:9783c9632aa40ee25fd78f',
    messagingSenderId: '1014655734942',
    projectId: 'thilshan-spotify',
    storageBucket: 'thilshan-spotify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC0Jv43PcLMzy-mMmuhkflurHkNtgdL_M',
    appId: '1:1014655734942:ios:d006449e88fd769d5fd78f',
    messagingSenderId: '1014655734942',
    projectId: 'thilshan-spotify',
    storageBucket: 'thilshan-spotify.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC0Jv43PcLMzy-mMmuhkflurHkNtgdL_M',
    appId: '1:1014655734942:ios:d006449e88fd769d5fd78f',
    messagingSenderId: '1014655734942',
    projectId: 'thilshan-spotify',
    storageBucket: 'thilshan-spotify.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUIXY0RwjNeGmJRU9umNu0Q87Ghfdiink',
    appId: '1:1014655734942:web:57efd6975bc3cdab5fd78f',
    messagingSenderId: '1014655734942',
    projectId: 'thilshan-spotify',
    authDomain: 'thilshan-spotify.firebaseapp.com',
    storageBucket: 'thilshan-spotify.firebasestorage.app',
  );
}
